### PR TITLE
WIP: Switching over to ESLint from JSHint

### PR DESCRIPTION
**Pull request by paazmaya**
Related to #1133.

So far the ESLint configuration has been made so that the rules found from earlier JSHint configuration are matched and set to trigger an error (2).
All the rest are set to trigger warning (1) and need further discussion of how the configure them.

There are plenty of inline configurations in the JS files, specifically in the tests, which could be possibly reduced.

Please comment.

### CODE REVIEW

**Comment by paazmaya** [comment]
@n1k0 @mickaelandrieu any comments on this?

If nothing major, feel free to merge, as it is easier to continue adjusting the rules once the new tool in taken in use.

**Comment by mickaelandrieu** [comment]
@paazmaya  for now the build seems broken.

**Comment by paazmaya** [comment]
@mickaelandrieu due to 38 linting errors found by ESLint. I could either fix those (and create conflicts for many other PRs) or tune down the lint configuration so they appear as warnings (and fix them later...).

**Comment by mickaelandrieu** [comment]
@paazmaya I agree to switch too, and "turn down" for now lint configuration (with a technical debt issue, of course)

**Comment by paazmaya** [comment]
@mickaelandrieu green light acquired!

**Comment by mickaelandrieu** [comment]
can you squash your commits ? I merge :)

Thank you for this contribution @paazmaya

**Comment by jefleponot** [comment]
Hello Everybody,

Here is the score on my repository casperjs :
- With eslint have got ✖ 11104 problems (11104 errors, 0 warnings)- Strings must use doublequote lol
- With jshint have got ✖ 20 errors  (This function's cyclomatic complexity is too high)

Regards :-p

**Comment by paazmaya** [comment]
@mickaelandrieu now is in single :bride_with_veil:

**Comment by mickaelandrieu** [comment]
thank you @paazmaya :)

**Pull request merged**
