### PR TITLE
Refs #525 html5 multiple file input support

### PR DESCRIPTION
**Pull request by albuquerque**
Added support to upload multiple files at once.
New test added to test the feature.

Code is refactoring and cleanup of pending pull request refs #526  which seems to have been abandoned by the original author.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,

thank you for your contribution. Would you mind to squash your commits into one with a meaningful label - like "added support for multiple file input" for instance ?

Mickaël

**Comment by albuquerque** [comment]
Hi @mickaelandrieu 

Squashed as requested. I hope it is right as I am doing this for the first time.

Regards,
Sam

**Comment by mickaelandrieu** [comment]
Not realy :D, try this:

1) use git log to get the commit before your very first commit (ie the 
```bash
git rebase -i 40213c2c
```

and replace every "pick" by "s" in the  open window except for the first commit ("Added support for multiple file uploads").

Then you need to push force the branch

```bash
git push -f origin refs-525-HTML5-multiple-file-input-support
```

Mickaël

**Comment by albuquerque** [comment]
HI @mickaelandrieu,

Followed your instructions. I had to use git commit --amend --allow-empty as it was throwing an "Aborting commit due to empty commit message" error. 

However, it's now showing three additional files that are not part of my changes.
src/casperjs.cs
tests/clitests/runtests.py
tests/clitests/scripts/options.js

- Sam

**Comment by mickaelandrieu** [comment]
Yes, because your repository is not synced with n1k0's one.

```
git remote add casperjs https://github.com/n1k0/casperjs.git
git fetch casperjs
git checkout refs-525-HTML5-multiple-file-input-support
git rebase -i casperjs/master
git push -f origin refs-525-HTML5-multiple-file-input-support 
```

Mickaël

**Comment by mickaelandrieu** [comment]
damn, tests are now broken :/

I don't realy know why to be honest /c @istr

**Comment by istr** [comment]
> damn, tests are now broken :/

That is an intermittent error (popup problem #1354), we'll hopefully have fixed very soon (root cause found by @jefleponot).

**Comment by albuquerque** [comment]
Thanks for clearing that up @istr.
Thanks for the help with the commits @mickaelandrieu

**Comment by mickaelandrieu** [comment]
@istr implementation sounds good to me. :+1:

**Comment by istr** [comment]
@mickaelandrieu Seems complete, :+1: to merge. Could you please check if the PhantomJS 2.0.0 specific form  regression https://github.com/ariya/phantomjs/issues/12506 is documented somewhere in CasperJS?

**Comment by mickaelandrieu** [comment]
@istr for sure it's not documented even in Casper or in phantomJS docs :)

**Comment by istr** [comment]
Ok. Opened [a new issue](https://github.com/n1k0/casperjs/issues/1503) for engine quirks documentation. Merging this one.

**Pull request merged**
