### PR TITLE
Added link to Gitter

### PR DESCRIPTION
**Pull request by rdpanek**
Please @n1k0 create room at Gitter :+1:

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
I'm not sure ... I agree to get a gitter *but* I think this kind of decision is more up to @n1k0.

**Comment by paazmaya** [comment]
Perhaps this can be re-evaluated when the project moved under `casperjs` organisation?

**Comment by slang800** [comment]
:-1: - Gitter has no place in FOSS development. The last thing we need is another proprietary chat network, especially since we already have ubiquitous IRC support.

**Comment by n1k0** [comment]
IRC is good enough.

**Pull request closed without merging**
