### PR TITLE
Update .eslintrc to fix Travis CI error

### PR DESCRIPTION
**Pull request by alexgibson**
Note I haven't tested this directly, just took a guess looking at the error.

### CODE REVIEW

**Comment by alexgibson** [comment]
This fixed one error, but looks like there are more. I'll see if I can update shortly.

**Comment by alexgibson** [comment]
Ok, worked out there are some inline eslint comments in the Casper code that look to be invalid. I can work through these next week, as well as tidy up these commits.

**Comment by alexgibson** [comment]
Should probably also tell Travis to only install a specific version of eslint to prevent future breakages happening again.

**Comment by alexgibson** [comment]
Ok this now fixes the Travis build errors - @n1k0 can you please merge this?

**Comment by n1k0** [comment]
Thanks.

**Comment by alexgibson** [comment]
@n1k0 - happy to help, thank you!

**Pull request merged**
