### PR TITLE
Bug fix for #1275 : adding missing conversion to string

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by istr** [comment]
Would you mind adding a simple test to ```tests/suites/casper/formfill.js``` that references the original issue #1275?

I will merge this when there's a test included demonstrating that this issue is resolved by this PR (even though the fix itself is trivial).

Thanks.

(This points to a general problem with "type safety" in ```setField``` and and thus ```fill```. More tests and more robust "convert to string" policy would be nice to have.)

**Comment by Lucas-C** [comment]
Done !

**Comment by istr** [comment]
@paazmaya,  @hexid Please have a short look. I would like to merge this.

**Comment by mickaelandrieu** [comment]
:+1: this make sense

**Comment by istr** [comment]
@mickaelandrieu Ok, thank you. Sorry that I missed to address you personally, too.

**Comment by mickaelandrieu** [comment]
@istr it's OK,  I'm not very active ;)

**Pull request merged**
