### PR TITLE
added official PhantomJS 2.1.1 build to travis

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hi,

I've noticed @ariya have bumped an official 2.1.1 build for PhantomJS 2.1.1.

Let's add it in our own build stack :)

Mickaël

### CODE REVIEW

**Comment by istr** [comment]
Great! Could you please replace [the link to my inofficial build](https://github.com/n1k0/casperjs/blob/master/.travis.yml#L91) with the link to the official release in this PR?

Thank you.

**Comment by istr** [comment]
Ok, I restarted the failing test. The new engine still fails two of the client tests. This needs investigation.

**Comment by mickaelandrieu** [comment]
@istr yup I clearly don't know how to fix it /c @n1k0 

I'd would like to keep your unofficial build because you test 2.0.1 and the PhantomJS team didnt (yet) publish an official build for this release :)

**Comment by istr** [comment]
Ok, then let's keep the unofficial 2.0.1 but add the official 2.0.0, too.

I will try to see what happens in the failing tests.

**Comment by istr** [comment]
Please find attached a patch that fixes the clitest for 2.1.1. It seems that this build (version?) neither reports line numbers nor code fragments in the stack trace. I am not yet sure why, but remember similar situations where removing the reported line number fixed the test for 2.0.0 and 2.0.1.

```patch
diff --git a/tests/clitests/runtests.py b/tests/clitests/runtests.py
index 20823d0..0f1ae27 100644
--- a/tests/clitests/runtests.py
+++ b/tests/clitests/runtests.py
@@ -347,8 +347,7 @@ class TestCommandOutputTest(CasperExecTestBase):
             '# true',
             'FAIL Subject is strictly true',
             '#    type: assert',
-            '#    file: %s:3' % script_path,
-            '#    code: test.assert(false);',
+            '#    file: %s' % script_path,
             '#    subject: false',
             'FAIL 1 test executed',
             '0 passed',
@@ -365,7 +364,7 @@ class TestCommandOutputTest(CasperExecTestBase):
             '# step throws',
             'FAIL Error: oops!',
             '#    type: uncaughtError',
-            '#    file: %s:5' % script_path,
+            '#    file: %s' % script_path,
             '#    error: oops!',
             'FAIL 1 test executed',
             '0 passed',
@@ -444,8 +443,7 @@ class TestCommandOutputTest(CasperExecTestBase):
             '# true',
             'FAIL Subject is strictly true',
             '#    type: assert',
-            '#    file: %s:3' % failing_script,
-            '#    code: test.assert(false);',
+            '#    file: %s' % failing_script,
             '#    subject: false',
             'Test file: %s' % mytest_script,
             'PASS ok1',
```

**Comment by istr** [comment]
@mickaelandrieu ping... Would you mind integrating my patch in your PR to see if it works? Thank you.

**Comment by mickaelandrieu** [comment]
@istr sorry for delay, it's now done and I've checked it works with phantomjs 2.1.1 (my actual version).

Also, I've cleaned the `.travis.yml` file.

Mickaël

**Comment by istr** [comment]
@mickaelandrieu Thank you! :+1: Merging. No need for excuses though -- everybody should be happy and thankful for your support. :-)

**Comment by mickaelandrieu** [comment]
@istr are we ready for beta 4 ? :) I think you've empowered me to a real come back into CasperJS project ^^

**Comment by istr** [comment]
From my point of view we could publish master as beta 4.

We would need @n1k0  to [```npm owner add <user> casperjs```](https://docs.npmjs.com/cli/owner) at least one of us, so we are allowed to push a new version. My [npm user is istr](https://www.npmjs.com/~istr).

**Comment by mickaelandrieu** [comment]
I agree, and I prefer to see you (and @n1k0) be in charge ;)

**Comment by n1k0** [comment]
@istr added you as a npm collaborator for casperjs on npm :)

**Pull request merged**
