### PR TITLE
sendKeys: explain how to send special keys

### PR DESCRIPTION
**Pull request by denis-sokolov**

### CODE REVIEW

**Comment by denis-sokolov** [comment]
Seems this will never be merged.

**Comment by mickaelandrieu** [comment]
Please re open, we are only 2 actives maintainers and need time to review each contribution..

**Comment by denis-sokolov** [comment]
I can’t, I deleted the fork. The diff still shows my suggestions if you choose to include them in the project.
No hard feelings, I was cleaning up my forks. :)

**Comment by mickaelandrieu** [comment]
Ok,  sorry for delay we need more hands :/

Thank you for contributing

**Comment by istr** [comment]
ping @BIGjuevos: a candidate for "re-PR".

**Pull request closed without merging**
