### PR TITLE
refs #525 Allow to upload multiple files at once

### PR DESCRIPTION
**Pull request by nikrou**
I wrote a simple test.
The code to be updated is in fillForm() method and can be surely improved.

### CODE REVIEW

**Comment by albuquerque** [comment]
I came across this when trying to upload multiple files to an HTML5 file type input element. Applying the changes in casper.prototype.fillForm and the new function casper.prototype.getFileFieldSelector makes the functionality work. I understand that there are some minor coding standard issue. I am not sure if @nikrou has any plans to submit and update especially since it's more than 2 years old. Could the issues be fixed and merged please?

**Comment by mickaelandrieu** [comment]
@albuquerque can you apply the update in a new pull request and submit it ?
@istr is (mostly) the only active maintainer (no offense, others: you are all great :).

It's the best chance to get this feature accepted atm :+1:

**Comment by albuquerque** [comment]
Will do @mickaelandrieu. I didn't touch the tests. Will update it and submit.

**Comment by istr** [comment]
Abandoned. Closing in favor of #1425 that is about to be merged.

**Pull request closed without merging**
