### PR TITLE
added phantomjs2 to the travis build

### PR DESCRIPTION
**Pull request by mickaelandrieu**
This is a first step before try to support phantomjs2.

/!\ don't merge it, this need to be splitted into multiples pull requests

- [ ] fixed eslint configuration
- [ ] add phantomjs 2
- [ ] allow failures on phantomjs 2

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @paazmaya I don't know why but eslint configuration is totaly broken, can you help me ?

**Comment by alexgibson** [comment]
Pull #1298 fixes the eslint breakage.

**Comment by alexgibson** [comment]
If you rebate this branch against master the eslint issue should now be fixed :+1:

**Comment by mickaelandrieu** [comment]
I will make a new PR, this one is totaly broken :)

**Pull request closed without merging**
