### PR TITLE
Add downloadBinary for download file correctly.

### PR DESCRIPTION
**Pull request by ethaizone**
I use download() to download csv and it make content gone wrong.

Ref: http://stackoverflow.com/questions/20599422/casperjs-issue-downloading-csv-file

### CODE REVIEW

**Comment by ethaizone** [comment]
If this pull request is not good, you can close it but I hope we can have better solution for it.

**Comment by istr** [comment]
Basically it could be a good idea -- however test cases and updated documentation is missing.

**Comment by mickaelandrieu** [comment]
@ethaizone I'm not sure we need a new method, it's better to improve the `download` function with new tests regarding the specific use cases you've met.

**Comment by ethaizone** [comment]
@mickaelandrieu I think same as you but I don't know another solution so I want to tell that I found this problem too. I hope we can have better download function. I look into test case and found base64 encode is good for multi-media files too. 

I think if we can improve download(), it will better but at currently I don't have any idea.

PS. Today is first day for me to try write js testcase. Travis tell failed but it's fun. lol

**Comment by ethaizone** [comment]
I test again and found this implement broke xlsx files so I will close this pull request.

**Pull request closed without merging**
