### PR TITLE
Update casper.js

### PR DESCRIPTION
**Pull request by soundyogi**
If "fillForm" could "return this" we could chain it like most other methods.

### CODE REVIEW

**Comment by istr** [comment]
Please rebase your PR against current master. Build failures seem to be spurious eslint problems and a "chainable" ```fillForm``` is nice to have.

**Comment by soundyogi** [comment]
Hi,
so this is my first ever attempt to rebase a PR so perhaps you could have a quick look if this makes sense:

I cloned the casper repo
I added my fork with the path as remote
I checkout patch-1 branch
head was detached so I:
git checkout -b fillFormPatch

What would I do now? I have read something about forcepushing.

Thank You for your help with this very tiny PR :)

**Comment by istr** [comment]
There are lots of good pointers how to do this, e.g.
- https://help.github.com/articles/syncing-a-fork/
- https://robots.thoughtbot.com/keeping-a-github-fork-updated
- http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository
- https://2buntu.com/articles/1459/keeping-your-forked-repo-synced-with-the-upstream-source/

**Comment by soundyogi** [comment]
Perfect, thank you I just could not find anything useful
(keywords: "github pull request rebase")

I will read those and hopefully I will manage.

Thanks

**Comment by soundyogi** [comment]
Hope this is correct :_D

**Comment by mickaelandrieu** [comment]
@soundyogi would you mind to squash your commits ? Or I can do it

**Comment by soundyogi** [comment]
@mickaelandrieu 
sorry for responding so late

I had to learn how to squash commits first ._.

Again, I hope everything is correct :)

**Comment by mickaelandrieu** [comment]
:+1: thank you @soundyogi :) 

@istr thanks for review

**Comment by soundyogi** [comment]
No thank you! I learned very much about contirbuting to an Open Source Project.

Thanks for your patience - as this PR was really small - laughable even.
:)

**Pull request merged**
