### PR TITLE
Bump to version 1.1.0

### PR DESCRIPTION
**Pull request by istr**
I would like to publish 1.1.0-beta6, mainly to publish the updated documentation at http://docs.casperjs.org/en/latest/ ("read the docs" updates when publishing a new release).

@mickaelandrieu @BIGjuevos Please have a look at https://github.com/n1k0/casperjs/releases to review the draft entry and see if you are ok with this. Thank you.

### CODE REVIEW

**Comment by BIGjuevos** [comment]
Looks good. You beat me to the punch on this. Was planning on doing so next week.

**Comment by istr** [comment]
@BIGjuevos Feel free to actually merge this PR, grab the draft and publish it yourself if @mickaelandrieu approves it. :-)

Maybe I am offline tomorrow.

**Comment by BIGjuevos** [comment]
Ok. I'll finish it up once he approves.

**Comment by mickaelandrieu** [comment]
:+1: to be honest, why beta-6 and not the stable release ?

Except if I'm wrong, we dont have any blocker, let's just do it :)

**Comment by BIGjuevos** [comment]
We do have 4 open issues in the milestone.  I'll bump to 1.1 and move the remaining issues out to 1.2.

Any objections for me to add myself to the team list on the homepage while doing this as well?

**Comment by mickaelandrieu** [comment]
=> https://github.com/n1k0/casperjs/pull/1518

I assign myself to https://github.com/n1k0/casperjs/issues/777, let's do it, let's release 1.1 ASAP !
https://www.youtube.com/watch?v=ZXsQAXx_ao0

**Comment by istr** [comment]
> We do have 4 open issues in the milestone. I'll bump to 1.1

Why the sudden haste? A released version should have at least a ```package.json``` that is in sync with the version published at github, so we may publish the npm 1:1 from the same commit.

Any valid reason you published 1.1 without bumping the version? This PR was exactly in place to achieve this -- it should have been replaced with a similar PR *before* tagging the commit 1.1.
:-/

I know that ```-beta6``` sounds not that "sexy", but it indicates clearly that we have known bugs (and even regressions against ```-beta3``` for Windows) we would like to address to say it is "production ready".

If it could be done, I'd rather "un-publish" this release and at least amend the bumped version so we have the same commit for the *.tar.gz / *.zip and the npm.

**Comment by BIGjuevos** [comment]
We can un-publish the release.  This is git, everything is reversible.  

If we are going to stick with -beta6, did we want to bring in the issue to fix the windows regression?

**Comment by mickaelandrieu** [comment]
@istr I do agree with you, this is why I take one of the last issues we have to help the final release, I'm not against `beta-6` :)

I think we can finish the last issues and move on to 1.1: my concern is more "should we publish now beta6 and wait for 1.1, or wait for 1.1 that is coming very soon ? "

**Comment by istr** [comment]
> my concern is more "should we publish now beta6 and wait for 1.1, or wait for 1.1 that is coming very soon ? "

My concern is: let us publish *anything* asap, but let's keep consistency. :-)

I am ok with opting for 1.1 *now*, but if so -- please let us just
1. cleanly move the open issues to the next milestone
2. adjust the ```package.json``` to the release number we agree upon
3. release that version number here
4. create the npm from the same commit

in that order.

**Comment by mickaelandrieu** [comment]
@istr of course I didn't say we have to publish now :)

**Comment by istr** [comment]
@mickaelandrieu I would like to publish what we have *now* (today or tomorrow the latest), mainly to update the "latest" public docs we have online at http://docs.casperjs.org/en/latest/.

However, it seems that this did not happen for the other beta-versions anyway (if you have a look at the docs, you'll see that "latest" does not contain the updated quickstart document http://docs.casperjs.org/en/latest/quickstart.html).

Let us vote on the version -- I will then update this PR and the published revision number accordingly.

**Comment by istr** [comment]
Vote here (+1 reaction) for 1.1.

**Comment by istr** [comment]
Vote here (+1 reaction) for 1.1-beta6

**Comment by istr** [comment]
@n1k0 @mickaelandrieu @hexid @BIGjuevos any idea / hint how to trigger an update of the "read the docs" documentation?

**Comment by n1k0** [comment]
In theory they're rebuilt and published every time master is updated. I can probably give you access to their admin console, let me see.

**Comment by n1k0** [comment]
@istr @BIGjuevos could you please give me your readthedocs.org username (or create one) so I can add you to the list of maintainers? Thanks.

**Comment by BIGjuevos** [comment]
@n1k0 - Same username as here on GitHub: BIGjuevos

**Comment by istr** [comment]
@n1k0 - Same username as here on GitHub: istr
:-)

**Comment by n1k0** [comment]
You've been both added as well as @mickaelandrieu.

**Comment by BIGjuevos** [comment]
@n1k0 - thanks!  It looks like we can publish specific versions straight from the admin panel.

Am I all clear to move the remaining issues out of the 1.1 milestone?

**Comment by istr** [comment]
> Am I all clear to move the remaining issues out of the 1.1 milestone?

Yes, the vote was clear. :-)

**Comment by istr** [comment]
@n1k0 Thank you!

It seems that we
- just need to tag the "latest" version appropriately so it is rebuilt automatically
- the other versions to be published need to be selected manually from the admin panel

**Comment by n1k0** [comment]
You have all my trust to make the release. Just ping me when you want to migrate everything to the org, which was the initial plan IIRC.

**Comment by BIGjuevos** [comment]
> It seems that we
> just need to tag the "latest" version appropriately so it is rebuilt automatically
> the other versions to be published need to be selected manually from the admin panel

Looks like that has already been done looking at the panel.

> > Am I all clear to move the remaining issues out of the 1.1 milestone?

> Yes, the vote was clear. :-)

Wanted to make sure we weren't duplicating work and stepping on each others feet. :)  Things have been happening in parallel.

**Comment by BIGjuevos** [comment]
> You have all my trust to make the release. Just ping me when you want to migrate everything to the org, which was the initial plan IIRC.

Is after this release a good time to do the migration?  I volunteer to help out with the required changes.

**Comment by n1k0** [comment]
> I volunteer to help out with the required changes.

That's god to hear as I've lost track of what's needed, and don't have much time to handle this. I can press buttons when asked to, though :)

**Comment by istr** [comment]
@BIGjuevos @mickaelandrieu Could you please merge this? I will then update the released commit, the git tags (1.1 and latest) and prepare the npm packaging / releases. Thanks.

**Comment by mickaelandrieu** [comment]
@istr 1.1.0 remains a "pre release" ? https://github.com/n1k0/casperjs/releases/tag/1.1

**Comment by BIGjuevos** [comment]
It's a matter of un-ticking a box in the release.  @istr volunteered to mash the buttons after it was merged.

**Pull request merged**
