### PR TITLE
SlimerJS has some options that start with - instead of -- and CasperJS w...

### PR DESCRIPTION
**Pull request by DarrenCook**
(see mailing list thread "How to pass params to the engine?")

### CODE REVIEW

**Comment by paazmaya** [comment]
Could you provide a link to the (archived) mailing list thread mentioned?

**Comment by paazmaya** [comment]
@DarrenCook any updates on the mailing list thread?

**Comment by DarrenCook** [comment]
https://groups.google.com/forum/#!topic/casperjs/BMvdJ0kYPok

(first hit on google ;-)

**Comment by paazmaya** [comment]
Could you update this PR on top of current `master` ?

**Comment by istr** [comment]
Closing in favor of rebased merged PR #1507.

**Pull request closed without merging**
