### PR TITLE
[WIP] Add basic PhantomJS v2.x support (drops v1.x)

### PR DESCRIPTION
**Pull request by hexid**
Removed patchRequire() as it is no longer needed for 2.x
Removed coffeescript tests as v2.x removed support
Removed custom bind implementation as v2.x implements this
Switched from phantom.args to system.args as v2.x deprecated the former

I threw this together in response to #1299.
There are currently 8 failed selftests, which I will try to investigate.

**Warning**: This PR removes support for PhantomJS pre-2.x.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Can be a CasperJS 2.x but if no one maintain...

**Comment by istr** [comment]
@hexid to you happen to remember the commit [that breaks slimerjs](https://travis-ci.org/n1k0/casperjs/jobs/81889166)? I am [halfway through with 2.0.0 / 2.0.1 support](https://github.com/istr/casperjs), but [currently running into the very same issue with slimerjs](https://travis-ci.org/istr/casperjs/jobs/92035069).

**Comment by hexid** [comment]
@istr This PR should have been closed a while back in favor of #1310.

That PR has support for 2.0.1 as well as the 1.9.x series.

It was brought up a while back that SlimerJS wasn't being tested #776 (should be fixed by my other PR).

I've been pretty busy lately, but I'll try to get some issues created over on the SlimerJS project so that the remainder of the tests can be fixed.

**Comment by istr** [comment]
Ok, thanks for the clue. Some of the failing tests are not issues with slimerjs but with the test suite itself. I am trying to fix as much as I can in my feature branch within the next few days, because I need 2.0 support in a current project and can take the time to address these issues.

**Comment by paazmaya** [comment]
@istr Would it be possible that the fixes you are making for SlimerJS test would be in a separate PR?
It would make it easier to review and merge

**Comment by istr** [comment]
Yes, of course... Will split into two feature branches.

**Comment by istr** [comment]
Submitted in PR https://github.com/n1k0/casperjs/pull/1351.

**Comment by istr** [comment]
@hexid @n1k0 Are you ok with removing the [stale branches phantomjs2 and phantomjs-2](https://github.com/n1k0/casperjs/branches) now?

**Comment by n1k0** [comment]
I have no objection.

**Pull request closed without merging**
