### PR TITLE
fix absolute path comand line on linux

### PR DESCRIPTION
**Pull request by jefleponot**
just solve this issue #1479

### CODE REVIEW

**Comment by istr** [comment]
I don't like the idea to fix this with a platform check, because the bug description and [your explanation](https://github.com/n1k0/casperjs/issues/1479#issuecomment-195312768) in #1479 suggest that this is simply a logical bug in the bootstrap / require logic.

Could you refactor this into a real bug-fix that corrects the order of ```require``` and ```phantom.casperScriptBaseDir``` to prevent this loop on all platforms?

**Comment by jefleponot** [comment]
@istr 
I don't know what is a "real bug-fix" 

Is it a  git command ?

Please, explain me

**Comment by jefleponot** [comment]
I just test on Windows 7, there is no loop at all, native fs.absolute works perfectly.

> absolute('c:/..') = absolute('c://..') = absolute('c://../..') = absolute('c:/../..') ===>   'c:/'
loop is break because  "baseDir === prevBaseDir"

I will propose you another solution that could suit you, let's commit a new PR.

**Comment by jefleponot** [comment]
Hi @mickaelandrieu or @istr 

> Test server url not found: /tests/site/non-existant.html (file: /home/travis/build/n1k0/casperjs//tests/site/non-existant.html) warning
on one test

Could you please relaunch travis integration ?

**Comment by istr** [comment]
This one looks good. :-D :+1: to merge.

**Comment by istr** [comment]
@mickaelandrieu Please have a quick look and merge. I would like to stick with the "four eyes" principle.

**Comment by mickaelandrieu** [comment]
@istr thanks for review and @jefleponot for contribution of course :)

**Comment by jefleponot** [comment]
:smiley: Hey men ! This is my first accepted PR in casperJS project (1/10)
Alleluia 

to thanks collaborators, I will develop now a really cool feature :+1:

**Pull request merged**
