### PR TITLE
Allow form fill to find select element values by their option elements text as well as value

### PR DESCRIPTION
**Pull request by andy-g**
Currently, using the form fill helper requires one to specify the values for a select element, but at times we may not know the value, but we will know the text of the option we want to select.

This will also make the test more legible, as the value specified in the test will be the same as the value the user would look for and choose in the browser.

I also added url matching to test that the correct multi-select values are being submitted

### CODE REVIEW

**Comment by andy-g** [comment]
From what I can see that last Travis result is an error (`Couldn't resolve host 'github.com'`) as opposed to the previous eslint failure. Would someone be able to kick off this run again? Thanks

**Comment by paazmaya** [comment]
Kicked :walking:

**Comment by andy-g** [comment]
Thanks

**Comment by n1k0** [comment]
Great patch, thanks.

**Pull request merged**
