### PR TITLE
refs #1497,#1203 - add two more known issues

### PR DESCRIPTION
**Pull request by BIGjuevos**
This addresses the request to document two other known issues as mentioned in #1497

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@BIGjuevos would you mind to add a note in installation section about coffeescript support ? :)

**Comment by BIGjuevos** [comment]
QuickStart or Installation?

**Comment by mickaelandrieu** [comment]
Maybe after the pre requisites => http://docs.casperjs.org/en/latest/installation.html#prerequisites

**Comment by BIGjuevos** [comment]
@mickaelandrieu After looking in the docs, I decided to update it in quick start as well as introduction.  Since I think both are valid points of entry and one or the other may be skipped.

**Comment by mickaelandrieu** [comment]
thank you @BIGjuevos !

**Pull request merged**
