### PR TITLE
Package 1.1.0-beta4

### PR DESCRIPTION
**Pull request by istr**
Branch to prepare 1.1.0-beta4, addressing #1365.

@n1k0 @mickaelandrieu @hexid @paazmaya If you prefer a branch in https://github.com/n1k0/casperjs (maybe better because you could update it) I will relocate it there.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @istr I don't think we need a dedicated branch for this beta, imo we should release 1.1.0 stable as soon as possible.

**Comment by istr** [comment]
@mickaelandrieu Ok, agreed. Maybe open an issue to collect which bugs to fix and create a 1.1.0 branch for the few remaining steps?

**Comment by mickaelandrieu** [comment]
@istr :+1:  yup! let me know when you want me to merge :)

**Comment by n1k0** [comment]
The changes look good to me.

**Comment by mickaelandrieu** [comment]
All green ! Do you want to clean your commit history before merge ?

**Comment by istr** [comment]
Rebased / merged. @mickaelandrieu If you are happy with this, feel free to merge.

I will then tag the merged master appropriately and prepare the packaging of it this evening.

**Comment by mickaelandrieu** [comment]
thank you very much  @istr !

**Comment by mickaelandrieu** [comment]
@istr no tag for 1.1-beta4 ?

**Comment by istr** [comment]
@mickaelandrieu See https://github.com/n1k0/casperjs/releases when logged in. Preparing the entry and change log there as a draft. I could push that tag now, if you like -- but it could be done automatically by means of publishing the release entry... :-)

**Comment by mickaelandrieu** [comment]
@istr :+1: and now let's work on 1.1 stable :D CasperJS is not dead!

**Comment by istr** [comment]
@mickaelandrieu Yes, indeed. Could you please have a short look at 
https://github.com/n1k0/casperjs/releases/tag/untagged-316151748ff029cd4245 before I publish it?
Thank you. :-)

The npm release will follow tomorrow, I am getting too tired and do not want to make avoidable mistakes there.

**Comment by mickaelandrieu** [comment]
It's good to me :)

**Comment by istr** [comment]
Ok. Published. npm packages follow soon.

**Comment by paazmaya** [comment]
This is great news! and great achievement, thank you @istr !

**Comment by n1k0** [comment]
A bunch of thanks @istr for having taken care of this, you rock :)

**Comment by istr** [comment]
Thanks... It was a pleasure for me. :-)
Let's see if/how we can re-gain some traction on this invaluable project.

BTW I [bumped the "hipstered" version to 1.1-beta4](https://github.com/n1k0/casperjs/commit/697e0ada02450bf89cc0d170bffd43034288febf) recently.

**Pull request merged**
