### PR TITLE
Fix assignment of options to engine vs script

### LINKED ISSUE #1384: Command line option problem on Windows
casperjs.cs incorrectly sends some command line options to the engine (phantomjs) instead of the the script. If an option name starts with the same letters as any engine option, it'll get sent to the engine. 

For example, any option that starts with --w, such as --whoops, will get sent to the engine:

> marc$ mono bin/casperjs.exe --whoops
--whoops "/Users/marc/Projects/NewStuff/casperjs-me/bin/bootstrap.js" --casper-path="/Users/marc/Projects/NewStuff/casperjs-me" --cli
Error: Unknown option: whoops

It works okay on Mac OS X:

> marc$ casperjs --version --whoops
1.1.0-beta3

I'll submit a Pull Request shortly that fixes the problem.

### PR DESCRIPTION
**Pull request by mepard**
Consider entire option name, not just initial chars. Fixes #1384.

### CODE REVIEW

**Comment by mepard** [comment]
Why did two jobs fail? In particular, why did a non-dot-net test fail, when it succeeded in my previous PR and this change only affected casperjs.cs? Suggestions are welcome.

(I'm new to Travis CI, BTW)

**Comment by istr** [comment]
The failed jobs are known (but unresolved) issues that tend to occur when travis is under high load. After a restart all jobs passed.

**Comment by mepard** [comment]
Thanks.

**Comment by istr** [comment]
Contains the change sets of https://github.com/n1k0/casperjs/pull/1387 and https://github.com/n1k0/casperjs/pull/1388.

**Comment by istr** [comment]
Looks ok; @paazmaya, @hexid, @mickaelandrieu, @n1k0 please give a second opinion and/or merge.

Merge this after https://github.com/n1k0/casperjs/pull/1388.

**Comment by istr** [comment]
Ping. Anybody having the chance to test this on windows? Sorry that I did not make it yet -- would like to accept this bug-fix being the last in a series of three.

**Comment by mepard** [comment]
I verified this on Windows, but it's my PR, so it would be great if someone else would check it as well.

It'd be great to get it merged. It fixes a nasty and mysterious problem when you run into it. Some custom command line options work fine on other platforms, but get "Error: Unknown option" on Windows and it's not clear why or which ones.

**Comment by istr** [comment]
Yes. Sorry, but I kind of running out of time right now... Don't expect me to check this before start of next week -- feel free to nag any of the other collaborators / maintainers about it... :-)

**Comment by hexid** [comment]
Was able to borrow a friend's Window box to test this and everything looks good.

@mepard Thanks for the contribution!

**Comment by mickaelandrieu** [comment]
Thanks @mepard for contribution & @hexid for testing :+1:

**Comment by istr** [comment]
Great! Thank you!

**Comment by mepard** [comment]
@mickaelandrieu You're welcome and thanks for testing it.

**Pull request merged**
